### ISSUE TITLE
Documentation typo leads to error

### ISSUE THREAD

**Issue by aeleuterio** [linode/python-linode-api#104]
Hey there,
The LinodeClient documentation has this example for get_types():
`type = client.linode.get_types(linode.Types.label == "Linode 1024")[0]`

Turn out there no **Types** atttribute, only **Type**.
It was all good when I changed that.

**Comment by aeleuterio** [comment]
Adding to my previous comment:

The documentation also uses client.linode.get_distributions(), but it seems to me like newer versions of the API don't even use distributions anymore. I was able to get a list of distributions by using client.get_images()

**Comment by aeleuterio** [comment]
Ok I have a couple more:

In `>>> l, pw = client.linode.create_instance(type, region, distribution="linode/debian8")
` it should be **image** instead of _distribution_

In `while not l.state == 'running':` it should be **status** instead of _state_

**Comment by Dorthu** [comment]
Thank for reporting these errors.  I'll make a PR to get the docs updated tomorrow, but those are going to be phased out shortly in favor of the upcoming [sphinx documentation](https://github.com/linode/python-linode-api/pull/101), which you might also find useful.

**Comment by Dorthu** [comment]
The documentation has been moved to [Read the Docs](http://python-linode-api.readthedocs.io/en/latest/), where I believe it to be accurate.  Closing this issue.
