### ISSUE TITLE
Disks not created

### ISSUE THREAD

**Issue by kirys** [linode/python-linode-api#11]
The py lib doc states that

> A Linode disk. These do not need to be created manually - deploy a linode with 
> client.create_linode(serv, dc, source=distribution) to have the API generate working disks for you. 

but this code:

```
serv = client.get_services(linode.Service.label == "Linode 2048")[0];
dc = client.get_datacenters()[0];
distro = client.get_distributions(linode.Distribution.label == "CentOS 7")[0];
(linode, password) = client.create_linode(serv, dc, source=distro);
linode.boot()

```
Create a linode with no disks

**Comment by Dorthu** [comment]
The provided sample code does create a linode with disks.

```python3
>>> serv = client.get_services(linode.Service.label == "Linode 2048")[0];
>>> dc = client.get_datacenters()[0];
>>> distro = client.get_distributions(linode.Distribution.label == "CentOS 7")[0];
>>> (linode, password) = client.create_linode(serv, dc, source=distro);
>>> linode.disks
PaginatedList (2 items)
>>> for d in linode.disks:
...   print(d.label)
...
CentOS 7 Disk
512 MB Swap Image
```

I'm going to close this as a non-issue.  If you are in fact experiencing a problem, please comment again with an example of how you created a linode with a `source` and didn't get disks.

**Comment by kirys** [comment]
well actually if I use that code the result I get from client.get_linodes() is this:

{'id': 'linode2019441', 'ips_collection': None, 'state': None, 'created': None, 'updated': None, 'total_transfer': None, 'disks': None, 'services': None, 'group': None, 'distribution': None, 'recent_backups': None, 'alerts': None, '_populated': False, '_client': <linode.linode_client.LinodeClient object at 0x7f58f693ce80>, 'configs': None, 'ips': None, '_last_updated': datetime.datetime(1, 1, 1, 0, 0), 'label': None, 'datacenter': None, 'backups': None}

**Comment by Dorthu** [comment]
Sorry I missed this update.  The related sets (disks, configs, etc) are lazy-loaded since they take an extra api request to get, so they will show up as `None` until accessed (this is similar to SQLAlchemy's default behavior).  I assume that's what you're seeing.  If you actually say `print(my_linode.disks)` does it still say `None`?

**Comment by kirys** [comment]
I cannot test the lib i got from pip (linode-api-4.0.5a0) doesn't seems to work.
ex:
this code 
`for la in client.get_linodes():		
	print(la.id)
	la.delete()`
generate this error:
`Traceback (most recent call last):
  File "./deleteAllLinodes.py", line 30, in <module>
    la.delete()
  File "/home/kirys/.local/lib/python3.5/site-packages/linode/objects/base.py", line 90, in delete
    resp = self._client.delete(type(self).api_endpoint, model=self)
  File "/home/kirys/.local/lib/python3.5/site-packages/linode/linode_client.py", line 82, in delete
    return self._api_call(*args, method=requests.delete, **kwargs)
  File "/home/kirys/.local/lib/python3.5/site-packages/linode/linode_client.py", line 27, in _api_call
    endpoint = endpoint.format(**{ k: quote(vars(model)[k], safe='') for k in vars(model) if 'id' in k })
  File "/home/kirys/.local/lib/python3.5/site-packages/linode/linode_client.py", line 27, in <dictcomp>
    endpoint = endpoint.format(**{ k: quote(vars(model)[k], safe='') for k in vars(model) if 'id' in k })
  File "/usr/lib64/python3.5/urllib/parse.py", line 712, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib64/python3.5/urllib/parse.py", line 737, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes`
