### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by yoshizzle** [linode/python-linode-api#112]
Don't have time to submit a PR right now, but the word information is misspelled here:

https://github.com/linode/python-linode-api/blob/dcf22c4399daf9ada4872eb0c4af4d055b5aba34/linode/linode_client.py#L711

**Comment by rmcintosh** [comment]
fix via https://github.com/linode/python-linode-api/commit/dbcb8044099ae3ea1a6cdfebba6cfdadb428c6a6
