### ISSUE TITLE
How to use pagination with library

### ISSUE THREAD

**Issue by f1gjam** [linode/python-linode-api#34]
Hi,

I can't seem to see how to use pagination with this library when a multi page result is return. Ideally, their should be a .next() to get the next page.

**Comment by f1gjam** [comment]
Providing some more detail, it seems that the function make_paginated_list only manages a single page/list of results and doesn't fetch the remaining data. So the returned paginated list only contains a single page of results

**Comment by Dorthu** [comment]
Additional pages are loaded automatically as needed by [PaginatedList](https://github.com/linode/python-linode-api/blob/master/linode/util/paginated_list.py#L3), which is returned by any listing endpoint.

For example, there are a lot of kernels:

```
curl 'https://api.linode.com/v4/linode/kernels'
{"total_pages": 8, "kernels": [<omitted for brevity>], "total_results": 180, "page": 1}
```

When we load them up in the python library, it looks like this: 

```python
>>> import linode
>>> client = linode.LinodeClient('unauthenticated') # kernels endpoint doesn't need a token
>>> kernels = client.linode.get_kernels() # fetch the first page, and metadata
>>> len(kernels) # we see the 'total_results' above as the length
180
>>> kernels[0] # this is already loaded - no api call is emitted
Kernel: linode/latest-2.6-32bit
>>> kernels[30] # there are only 25 items per page - this emits a call to ?page=2
Kernel: linode/3.19.1-x86-linode71
```

Iterating over a PaginatedList will iterate over all objects in the collection, without your code needing to worry about fetching individual pages - they are lazy-loaded as required.

**Comment by f1gjam** [comment]
Thank you for clarifying. The documentation, didn't really explain that well and looking at the PaginatedList it seems like it was returning a single page.

The pagination page in the documentation, should give more examples.

Thanks again
