### ISSUE TITLE
Network transfer

### ISSUE THREAD

**Issue by f1gjam** [linode/python-linode-api#35]
Hi,

I can see how to get total network transfer (allocated) "total_transfer", but I can't seem to find out to get "network transfer out used" 

Is this available?

**Comment by Dorthu** [comment]
I'm afraid the API V4 does not yet return used network transfer, so it's not available in this library yet either. However, I expect it to be returned by the API in the coming weeks, and we will introduce support here as soon as that happens.

If you'd like to leave this issue opened, I'll update it as soon as this feature is available.

**Comment by citaret** [comment]
Hi,

How can I get "transfer_used" and "transfer_used" values of the account instead of the individual host, as in the result from the linode-cli command?

`linode account show -j`

**Comment by Dorthu** [comment]
This can be accessed as follows:

```python
transfer = client.account.get_transfer()
```

**Comment by citaret** [comment]
I tested it in version 4.1.3b0, seems that this method is not implemented:
```
In [1]: import linode

In [2]: client = linode.LinodeClient('SECRET....')

In [3]: client.account.get_invoices()
Out[3]: PaginatedList (122 items)

In [4]: client.account.get_transfer()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-e8b5c027483f> in <module>()
----> 1 client.account.get_transfer()

AttributeError: 'AccountGroup' object has no attribute 'get_transfer'
```

**Comment by Dorthu** [comment]
Sorry, this feature is on master but I haven't made a new release for it yet. It will be available in 4.1.3b1, or you can install it from source to get it early

**Comment by citaret** [comment]
I test the function in 4.1.3b1, it works, however, the value does not match the output of command line 'linode account show -j', maybe I misunderstood the meaning of some variables:

```
In [30]: t = client.account.get_transfer()

In [31]: t.used / t.quota
Out[31]: 0.8429962513586052

In [32]: t.used / t.max
Out[32]: 0.6767236467236467

In [33]: ret = subprocess.getoutput("linode account show -j")

In [34]: s = json.loads(ret)['info']

In [35]: s['transfer_used'] / s['transfer_pool']
Out[35]: 0.8042381283572814

In [36]: s
Out[36]:
{'balance': 0,
 'billing_method': 'metered',
 'managed': False,
 'request_action': 'show',
 'request_error': '',
 'transfer_billable': 0,
 'transfer_pool': 1351540,
 'transfer_used': 1086960}

In [37]: t.used
Out[37]: 950120

In [38]: t.quota
Out[38]: 1127075

In [39]: t.max
Out[39]: 1404000
```

**Comment by f1gjam** [comment]
Thank you :)
