### ISSUE TITLE
clone method missing

### ISSUE THREAD

**Issue by AdemKerenci** [linode/python-linode-api#40]
Hello,

I am trying to create a golden image from the following link: 
https://www.linode.com/docs/platform/automating-server-builds

I have found clone method from restful API:
https://developers.linode.com/v4/reference/endpoints/linode/instances/:id/clone

But, there is no clone method of linode object:
for python API: https://developers.linode.com/v4/libraries/python/linode

I have also checked the code but still no clone method, Can you help how can I do golden image with python API.

**Comment by Dorthu** [comment]
Sorry I missed it - just put it in.  I'll get documentation up soon, but the parameters closely match the api's.  Here's a quick rundown: 

#### Clone to New Linode

```python3
source_linode = client.linode.get_instances(Linode.label == 'source-linode').first()
source_linode.clone(region="us-east-1a", service="g5-standard-1", label="destination-linode")
```

#### Clone to an Existing Linode

```python3
source_linode = client.linode.get_instances(Linode.label == 'source-linode').first()
destination_linode = client.linode.get_instances(Linode.label == 'destination-linode').first()
source_linode.clone(to_linode=destination_linode)
```

**Comment by AdemKerenci** [comment]
Thank you for quick answer, I hope it will help me.

**Comment by Dorthu** [comment]
No problem!  The code hasn't been put into a release yet, so to use it immediately you'll need to [build from source](https://github.com/linode/python-linode-api#building-from-source) (don't worry, it's pretty painless - you may need to `pip uninstall linode-api` before doing it though).

**Comment by AdemKerenci** [comment]
I tried to clone a new node, it works fine but the only problem is even if I passed the label parameter it does not create new linode with the given label parameter instead it gives some default number like linode<some-numbers>. Can u try the code and reply to me?

**Comment by jamesottinger** [comment]
@AdemKerenci, although the docs list the full options, the "label", "group", and "with_backup" options are still awaiting changes on the backend. Those will be available soon and will resolve this issue.

**Comment by AdemKerenci** [comment]
Thanks again.

15 Ağu 2017 17:54 tarihinde "James Ottinger" <notifications@github.com>
yazdı:
