### ISSUE TITLE
Filtering on regions

### ISSUE THREAD

**Issue by gummiboll** [linode/python-linode-api#46]
Hello!

Regions doesn't seem to have a label (any more?), so when I try to filter on label (according to https://developers.linode.com/v4/libraries/python/linode-client) I get a error. Not a major issue since I can just loop through every region returned from `get_regions()` and compare there but would be nice to have this working.

```
>>> region = c.get_regions(linode.Region.label.contains("Newark"))[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Region' has no attribute 'label'
```

**Comment by gummiboll** [comment]
After talking to linode's support (ticket 8747969) I've learnt that the label on regions are depricated so closing this issue.

**Comment by Dorthu** [comment]
Sorry for the confusion, I'll update the guide
