### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by garrettjj** [linode/python-linode-api#49]
Issue when calling create_instance, throwing:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\linode\linode_client.py", line 98, in create_instance
    'type': ltype.id if issubclass(type(ltype), Base) else ltype,
TypeError: 'module' object is not callable`

Works normally in 4.1.3b0, appears to be related to:
https://github.com/linode/python-linode-api/commit/e83c22b7a41b07ce7c7f6651e7488413bbf416ef#diff-f7b7c5857f55aaabd12a661a63d5a23c

**Comment by Dorthu** [comment]
This was closed in https://github.com/linode/python-linode-api/commit/227e9526eaa13cfcb9c239a1ce2c1623013990f7, and deployed in 4.1.3b2
