### ISSUE TITLE
Login from console application

### ISSUE THREAD

**Issue by adontz** [linode/python-linode-api#51]
Hi

I have create personal access token and tried to use it as

    lc = LinodeClient(personal_access_token)
    domains = lc.get_domains()

but get "linode.errors.ApiError: 401: Invalid OAuth token;" message.

How should I login in unattended manner from console script?

**Comment by Dorthu** [comment]
That should work - is this still an issue?

**Comment by adontz** [comment]
No, I am not really sure what was wrong.
