### ISSUE TITLE
enum34 is not meant for >=python3.4

### ISSUE THREAD

**Issue by ryanm101** [linode/python-linode-api#58]
he enum34 package is incompatible with Python 3.6's enum implementation. This breaks Python processes depending on import order

**Comment by Dorthu** [comment]
Yikes, I'll get this sorted out and released tomorrow.

**Comment by ryanm101** [comment]
Cool would you please update this ticket with which release the fix will be in so i can grab that one from pip?

**Comment by Dorthu** [comment]
This should be fixed in v4.1.4b2 - please confirm that the issue is fixed for you before I close this

**Comment by ryanm101** [comment]
All good now thanks
