### ISSUE TITLE
Get object by ID

### ISSUE THREAD

**Issue by adontz** [linode/python-linode-api#61]
Let's say I have ID of the object (Linode, Disk, etc) I have found no way to get object by ID

For now I am doing like this

    linode_result = _linode_client.get(Linode.api_endpoint.format(id=server_id), model=Linode)
    server_object = Linode(_linode_client, linode_result['id'], linode_result)

    linode_result = _linode_client.get(Disk.api_endpoint.format(linode_id=server_object.id, id=disk_id), model=Disk)
    disk_object Disk(_linode_client, linode_result['id'], server_object.id, linode_result)

which looks like missing API method, because __init__ parameters vary and for me looks like managements objects are meant to be instantiated by factories, not directly.

Did I miss a way to do this or is it really missing?

**Comment by Dorthu** [comment]
You can just construct the object with client and the ID and we do [here](https://github.com/linode/python-linode-api/blob/master/examples/install-on-linode/app.py#L57):

```python
from linode import Linode

server_object = Linode(_linode_client, server_id) # make a Linode object
# server_object will make an API request to load the object data the first time it is accessed

# derived objects are a little harder - anything with two IDs in its URL needs both in its constructor
disk_object = Disk(_linode_client, disk_id, server_id) # use the object's ID first, then the parent object's ID

# or you can access it via the relationship on the parent object
disk_object = server_object.disks[0] # or another index

**Comment by adontz** [comment]
Not quite the same. Is there a good way to force load without accessing any property? I mean, I can construct Linode, Disk or any other object with (already) non-existent ID and have no good way to get "not found" exception as soon as possible. I use _api_get() for now but taking into account underscore that method is not meant to be public API.

**Comment by Dorthu** [comment]
The best way to load it up immediately is to immediately access an attribute of it.. something like

```python
try:
   l = Linode(client, 123)
   l.label
except ApiError:
  logger.warning("Linode not found!")
```

**Comment by adontz** [comment]
Exactly, and this is very non-intuitive. I think something like

    def ensure_loaded(self):

would be nice

**Comment by Dorthu** [comment]
I think I can make that happen, I'll play with it tonight

**Comment by Dorthu** [comment]
I pushed this in v4.1.4b3
