### ISSUE TITLE
POST https://api.linode.com/v4/linode/instances

### ISSUE THREAD

**Issue by adontz** [linode/python-linode-api#72]
Quite often I get Error 500

Request

    POST https://api.linode.com/v4/linode/instances HTTP/1.1
    Host: api.linode.com
    User-Agent: python-linode-api/('4.1.4b3',) python-requests/2.18.4
    Accept-Encoding: gzip, deflate
    Accept: */*
    Connection: keep-alive
    Authorization: Bearer 6d..<removed intentionally>..fb
    Content-Type: application/json
    Content-Length: 96
    
    {"type": "g5-standard-1", "region": "us-east-1a", "distribution": null, "authorized_keys": null}

Response

    HTTP/1.1 500 INTERNAL SERVER ERROR
    Server: nginx
    Date: Tue, 31 Oct 2017 11:40:58 GMT
    Content-Type: application/json
    Content-Length: 49
    Connection: keep-alive
    X-OAuth-Scopes: linodes:delete,domains:delete,nodebalancers:delete,images:delete,stackscripts:delete,longview:delete,events:delete,tokens:delete,clients:delete,account:delete,users:delete,tickets:delete,ips:delete,volumes:delete
    X-Accepted-OAuth-Scopes: linodes:create
    X-Frame-Options: DENY
    Access-Control-Allow-Origin: *
    Access-Control-Allow-Methods: HEAD, GET, OPTIONS, POST, PUT, DELETE
    Access-Control-Allow-Headers: Authorization, Origin, X-Requested-With, Content-Type, Accept, X-Filter
    X-RateLimit-Limit: 10
    X-RateLimit-Remaining: 10
    X-RateLimit-Reset: -1
    Retry-After: -1509450059

    {"errors": [{"reason": "Internal server error"}]}

**Comment by Dorthu** [comment]
We've made some changes and have not been seeing this issue on our end since.  Can you verify it is no longer producing errors when you create linodes?

**Comment by adontz** [comment]
I do not experience this error anymore
