### ISSUE TITLE
POST https://api.linode.com/v4/linode/volumes

### ISSUE THREAD

**Issue by adontz** [linode/python-linode-api#85]
POST https://api.linode.com/v4/linode/volumes

returns {"errors": [{"reason": "Not found"}]}

While the same operation from admin panel succeeds
I noticed that admin panel calls https://cloud.linode.com/api/v4/volumes/ and not API endpoint.

So I have fixed URL in debugger to
POST https://api.linode.com/v4/volumes
and it worked! Is it server

Documentation was changed accordingly
https://developers.linode.com/v4/reference/volumes

Can you provide fix ASAP?

**Comment by rmcintosh** [comment]
This should be fixed in a short while via https://github.com/linode/python-linode-api/pull/82
