### ISSUE TITLE
Which repository to use? 

### ISSUE THREAD

**Issue by baimafeima** [linode/python-linode-api#89]
I am confused which repository is the right one when I want to install the linode-python libraries. This one here or https://github.com/tjfontaine/linode-python which appears to be older but with the exact name?

**Comment by Dorthu** [comment]
This library is for the Linode API V4, which is currently in beta, the other talks to the API V3. In general, I recommend using this library as it will eventually be the only supported version of the API, but during the beta period (which is coming to and end within this half of 2018, ideal in Q1), it is possible for upstream changes that are not backwards compatible, which may cause a breaking change in this library as well.  I try to minimize the impact of these, but it's not always possible or practical to do so.

For more information on the API V4, see https://developers.linode.com

For more information on the API V3, see https://linode.com/api

If you have any questions or issues using this library, please reach out by opening an issue.

**Comment by Dorthu** [comment]
The API v4 is no longer in beta, so this is now the preferred way to access it through Python.  I'm going to close this since it's not longer in flux.
