### ISSUE TITLE
Deploy disk_list change to pypi

### ISSUE THREAD

**Issue by eatonphil** [linode/python-linode-api#9]
Did a clean reinstall of this from pip and it still has the incorrect code fixed in #7. Could we get a redeploy of the pypi package?

**Comment by Dorthu** [comment]
You can see releases [here](https://github.com/linode/python-linode-api/releases).  I usually run a release in sync with the api updates (about every two weeks, see [the development blog](https://engineering.linode.com) for details).  If you need the latest master, you can [build it from source](https://github.com/linode/python-linode-api/blob/master/README.rst#building-from-source).
