### ISSUE TITLE
AttributeError: 'Region' object has no attribute 'label'

### ISSUE THREAD

**Issue by mathslimin** [linode/python-linode-api#99]
>>> for r in client.get_regions():
...     print(r.label)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/ROOT/src/anaconda2/envs/yowsup/lib/python3.6/site-packages/linode/objects/base.py", line 123, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'Region' object has no attribute 'label'

**Comment by displague** [comment]
The guide has not been updated with the current properties returned by the regions endpoint.
https://developers.linode.com/v4/reference/endpoints/regions (id and country are the only properties, today).

#77 will correct the guide.
